<?xml version="1.0"?>
<robot name="my_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="base_length" value="0.4064" />
    <xacro:property name="base_width" value="0.2794" />
    <xacro:property name="base_height" value="0.1397" />
    <xacro:property name="base_mass" value="5.0" />
    <xacro:property name="wheel_radius" value="0.034925" />
    <xacro:property name="wheel_length" value="0.0254" />
    <xacro:property name="wheel_mass" value="1.0" />
    <xacro:property name="lidar_stand_length" value="0.09525" />
    <xacro:property name="lidar_stand_width" value="0.06985" />
    <xacro:property name="lidar_stand_height" value="0.03175" />
    <xacro:property name="lidar_stand_mass" value="1" />
    <xacro:property name="lidar_length" value="0.0254" />
    <xacro:property name="lidar_radius" value="0.034925" />
    <xacro:property name="lidar_mass" value="0.5" />
    <xacro:property name="caster_mass" value="0.5" />

    <!--XARCROs FOR ARTICUBOT-->
    <xacro:macro name="lidar_stand_link">
        <link name="lidar_stand_link">
            <visual>
                <geometry>
                    <box size="${lidar_stand_length} ${lidar_stand_width} ${lidar_stand_height}" />
                </geometry>
                <origin xyz="0 0 ${lidar_stand_height/2.0}" rpy="0 0 0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <box size="${lidar_stand_length} ${lidar_stand_width} ${lidar_stand_height}" />
                </geometry>
                <origin xyz="0 0 ${lidar_stand_height/2.0}" rpy="0 0 0" />
            </collision>
            <xacro:box_inertia m="${lidar_stand_mass}" l="${lidar_stand_length}" w="${lidar_stand_width}" h="${lidar_stand_height}"
                           xyz="0 0 ${lidar_stand_height / 2.0}" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:macro name="lidar_link">
        <link name="lidar_link">
            <visual>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_length}" />
                </geometry>
                <origin xyz="0 0 ${lidar_length/2.0}" rpy="0 0 0" />
                <material name="black" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${lidar_radius}" length="${lidar_length}" />
                </geometry>
                <origin xyz="0 0 ${lidar_length/2.0}" rpy="0 0 0" />
            </collision>
            <xacro:cylinder_inertia m="${lidar_mass}" r="${lidar_radius}" h="${lidar_length}" 
                             xyz="0 0 0" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:macro name="wheel_link" params="prefix">
        <link name="${prefix}_wheel_link">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
            </collision>
            <xacro:cylinder_inertia m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" 
                             xyz="0 0 0" rpy="${pi / 2.0} 0 0" />
        </link>
    </xacro:macro>

    <xacro:macro name="base_link">
        <link name="base_link">
            <visual>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
                <material name="blue" />
            </visual>
            <collision>
                <geometry>
                    <box size="${base_length} ${base_width} ${base_height}" />
                </geometry>
                <origin xyz="0 0 ${base_height/2.0}" rpy="0 0 0" />
            </collision>
            <xacro:box_inertia m="${base_mass}" l="${base_length}" w="${base_width}" h="${base_height}"
                           xyz="0 0 ${base_height / 2.0}" rpy="0 0 0" />
        </link>
    </xacro:macro>

    <xacro:macro name="caster_wheel_link">
        <link name="caster_wheel_link">
            <visual>
                <geometry>
                    <sphere radius="${wheel_radius/2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="grey" />
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${wheel_radius/2.0}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertia m="${caster_mass}" r="${wheel_radius / 2.0}"
                            xyz="0 0 0" rpy="0 0 0" />
        </link>
    </xacro:macro>


    <!--INSTANCES OF XACROs-->
    <xacro:base_link/>
    <xacro:caster_wheel_link/>
    <xacro:wheel_link prefix="right" />
    <xacro:wheel_link prefix="left" />
    <xacro:lidar_stand_link />
    <xacro:lidar_link />

    <link name="base_footprint" />
lidar_mass
    <joint name="base_joint" type="fixed">
        <parent link="base_footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0"/>
    </joint>

    <joint name="base_right_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${-(base_width + wheel_length) / 2.0} 0" rpy="${pi/2} 0 0" />
        <axis xyz="0 0 -1" />
    </joint>

    <joint name="base_left_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_wheel_link" />
        <origin xyz="${-base_length / 4.0} ${(base_width + wheel_length) / 2.0} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1" />
    </joint>
    
    <joint name="base_caster_wheel_joint" type="fixed">
        <parent link="base_link" />
        <child link="caster_wheel_link" />
        <origin xyz="${base_length / 3.0} 0 ${-wheel_radius / 2.0}" rpy="0 0 0" />
    </joint>
    
    <joint name="base_lidar_stand_joint" type="fixed">
        <parent link="base_link" />
        <child link="lidar_stand_link" />
        <origin xyz="${base_height/2.0} 0 ${base_height}" rpy="0 0 0" />
    </joint>

    <joint name="lidar_stand_lidar_joint" type="continuous">
        <parent link="lidar_stand_link" />
        <child link="lidar_link" />
        <origin xyz="${-1.0*((lidar_stand_length/2.0)-lidar_radius)} 0 ${lidar_stand_height}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>
</robot>