<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <plugin filename="ignition-gazebo-diff-drive-system" name="ignition::gazebo::systems::DiffDrive">
          <left_joint>base_left_wheel_joint</left_joint>
          <right_joint>base_right_wheel_joint</right_joint>
          <wheel_separation>${base_width + wheel_length}</wheel_separation>
          <wheel_radius>${wheel_radius}</wheel_radius>
          <odom_publish_frequency>1</odom_publish_frequency>
          <max_linear_acceleration>5</max_linear_acceleration>
          <min_linear_acceleration>-5</min_linear_acceleration>
          <max_angular_acceleration>4</max_angular_acceleration>
          <min_angular_acceleration>-4</min_angular_acceleration>
          <max_linear_velocity>3.0</max_linear_velocity>
          <min_linear_velocity>-3.0</min_linear_velocity>
          <max_angular_velocity>3</max_angular_velocity>
          <min_angular_velocity>-3</min_angular_velocity>
          <topic>cmd_vel</topic>
          <publish_odom>true</publish_odom>
          <publish_odom_tf>true</publish_odom_tf>
          <publish_wheel_tf>true</publish_wheel_tf>
        </plugin>
        
        <plugin filename="ignition-gazebo-joint-state-publisher-system" name="ignition::gazebo::systems::JointStatePublisher"/>
    </gazebo>

</robot>