controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController
    
    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:

    publish_rate: 30.0 # You can set this higher than the controller manager update rate, but it will be throttled
    base_frame_id: base_link

    left_wheel_names: ['base_left_wheel_joint']
    right_wheel_names: ['base_right_wheel_joint']
    wheel_separation: 0.3048
    wheel_radius: 0.034925
    # odom_frame_id: 'base_footprint'

    use_stamped_vel: false

    # Added For ROS Control

    linear.x.max_acceleration: 5.0

    linear.x.min_acceleration: -5.0

    linear.x.max_velocity: 3.0

    linear.x.min_velocity: -3.0

    angular.z.max_acceleration: 4.0

    angular.z.min_acceleration: -4.0

    angular.z.max_velocity: 3.0

    angular.z.min_velocity: -3.0